### ISSUE TITLE
Converting a Multi-Page-PDF to multiple PNG files

### ISSUE THREAD

**Issue by Choppel** [mmomtchev/magickwand.js#34]
Hello,

I wanted to use node-magickwand to convert a PDF to separate PNG files.
In a terminal using the imagemagick cmd tool I can do this: 
`convert -density 150 in.pdf PNG32:out.png`
and this converts the PDF to out1.png, out2.png etc.

With node-magickwand I at least managed to get the first page like
```
let im = new Magick.Image(null);
await im.readAsync('in.pdf');
await im.magickAsync('PNG32');
const blob = new Magick.Blob();
await im.writeAsync(blob);
await writeFile('out.png', blob.data());
```

But how would I load the PDF with a density of e.g. 150 and save all pages with node-magickwand?

**Comment by mmomtchev** [comment]
In order to read all the pages of PDF document you must use the STL mehods:

```js
const list = await Magick.readImagesAsync('in.pdf');
const density = new Magick.Point(10);
list.forEach(im => im.density(density));
```

In case you haven't already read my profile, I am currently living in total isolation since I am being extorted by the French police and the French judiciary about a series of falsified criminal proceedings including false rape charges and sexual harassment. They are trying to cover up those affairs because they are linked to the personal problem of the man who is behind that affair and the fact that these have been organized with corruption of judicial officials. The French police came yesterday evening, without any official order and drew their guns in an attempt to further intimidate me. In order to show me that I have to shut up about that affair, people are simultaneously posting issues on my projects. Yours is one of these. You don't happen to know anything?

**Comment by Choppel** [comment]
Hi Momtchil,

first of all thank you for the example. It guided my in the right direction.

I am sorry to hear about that. I don't know anything about others posting issues on your projects. Sorry.
I really hope that you find the help you need to sort this thing out.

Thanks for your help nonetheless.
